//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.Management.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzure.Management.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Subscriptions version=&quot;1.0&quot; xmlns=&quot;urn:Microsoft.WindowsAzure.Management:WaPSCmdlets&quot;&gt;
        ///  &lt;Subscription name=&quot;mysub1&quot;&gt;
        ///    &lt;SubscriptionId&gt;279b0675-cf67-467f-98f0-67ae31eb540f&lt;/SubscriptionId&gt;
        ///    &lt;Thumbprint&gt;12D09EC0008EEE10C1B80AB70B3739E6BC509BB3&lt;/Thumbprint&gt;
        ///    &lt;ServiceEndpoint&gt;0853C43B56C81CE8FC44C8ACDC8C54783C6080E2&lt;/ServiceEndpoint&gt;
        ///    &lt;SQLAzureServiceEndpoint&gt;0853C43B56C81CE8FC44C8ACDC8C54783C6080E2&lt;/SQLAzureServiceEndpoint&gt;
        ///    &lt;CurrentStorageAccount&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string subscriptions {
            get {
                return ResourceManager.GetString("subscriptions", resourceCulture);
            }
        }
    }
}
